version: "3.9"

services:
  api:
    build: ./server
    env_file: ./server/.env
    expose:
      - "8080"              # internal only; web will proxy to this
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "80:80"             # public HTTP
    depends_on:
      - api
    restart: unless-stopped

